### ISSUE TITLE
Redirect from sources that are not Moodle URLs

### ISSUE THREAD

**Issue by VOOM108** [catalyst/moodle-tool_redirects#10]
Idea for an enhancement: 

I would like to redirect with "vanity" - URLs, in order to make certain target URLs easier to get to directly. 

Example: 

#/importantquiz/#=>/mod/quiz/view.php?id=18

with the result being: 
https://campus.mymoodlesite.com/importantquiz going to https://campus.mymoodlesite.com/mod/quiz/view.php?id=18

Could that functionality be added to the plugin? I would usually do this with redirect or ModRewrite in the .htaccess, but I would like to offer this possibility to admins in the GUI as well.

**Comment by dmitriim** [comment]
hey @VOOM108 
It should just work if https://campus.mymoodlesite.com/importantquiz is your moodle page that loads configs and has after_config callback fired, otherwise it's out of scope for that plugin sorry.

**Comment by brendanheywood** [comment]
If that page doesn't exist at all, but you have setup Moodle to be the handler for your error pages then this should all work.

The setup for this can be found here:

https://docs.moodle.org/dev/Error_pages

ie browser visits 

/importantquiz

this doesn't exist and so nginx or apache routes this to the error page at:

/error/index.php

From this page the after_config hook fires and does the detection and then redirects to wherever you want it to based on config

**Comment by brendanheywood** [comment]
I'm gonna reopen this and treat this as a documentation task to update the readme with an example of this

**Comment by VOOM108** [comment]
> If that page doesn't exist at all, but you have setup Moodle to be the handler for your error pages then this should all work.
> 
> The setup for this can be found here:
> 
> https://docs.moodle.org/dev/Error_pages
> 
> ie browser visits
> 
> /importantquiz
> 
> this doesn't exist and so nginx or apache routes this to the error page at:
> 
> /error/index.php
> 
> From this page the after_config hook fires and does the detection and then redirects to wherever you want it to based on config

I added 
`ErrorDocument 404 /error/index.php`
to the .htaccess and it did produce the Moodle error page instead of a simple server 404. However - the result with the redirect was not as expected... 

`#/importantquiz/#=>/mod/quiz/view.php?id=18`

![image](https://user-images.githubusercontent.com/16562946/212914604-48b4023f-5fdb-457d-bdda-c1b8bcdc5ddb.png)

**Comment by brendanheywood** [comment]
Ok this was actually a surprisingly deep rabbit hole but this is now all implemented in https://github.com/catalyst/moodle-tool_redirects/pull/15

If I have test config like this:
```
#\/vanity#=>/my/
``` 
then I get a redirect:
```
brendan@catau-bri-laptop0372 05:30:17 ~ $ curl -kI https://master.localhost/vanity
HTTP/1.1 303 See Other
...
X-Redirect-By: Moodle /admin/tool/redirects/classes/helper.php:119
Location: https://master.localhost/my/
```

**Comment by brendanheywood** [comment]
One caveat is that if you are using nginx then the error pages must be setup like this:

```nginx
error_page 403 = /error/index.php
```

and not just like below (the moodle wiki was not like this and is now corrected)

```nginx
error_page 403 /error/index.php
```
https://docs.moodle.org/dev/Error_pages
