### ISSUE TITLE
Use after_config callback to redirect earlier in the bootstrap

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_redirects#2]

**Comment by dmitriim** [comment]
@brendanheywood  what was the intention on this issue? I just saw it in the code and realised that the redirect won't work as $PAGE doesn't have any URL when  after_config gets called.

**Comment by dmitriim** [comment]
It actually caused https://github.com/catalyst/moodle-tool_redirects/issues/4 and we fixed it as https://github.com/catalyst/moodle-tool_redirects/blob/master/classes/helper.php#L104 

But this hook would never work anyway.

**Comment by brendanheywood** [comment]
Yeah you are right, but this hook could still work just by using the real url and not the $PAGE object

**Comment by dmitriim** [comment]
I'm trying to figure out what was the reason for this hook? Any issues using before_http_headers?

**Comment by brendanheywood** [comment]
I think before_http_headers is only called from a rendered page so there is a lot of edge cases it doesn't touch and after_config would get all of them. It was probably to avoid some situations with a double or triple redirect and make it faster

**Comment by dmitriim** [comment]
Can you think of any not rendered page/URL that we would like to redirect from?

**Comment by brendanheywood** [comment]
The one which jumps to mind is code which does some logic and then redirects somewhere else, eg sso, and we'd want this to trigger first. I really dunno and can't remember why I wanted this. I'm fine to revert it until we find and document a proper use case
