### ISSUE TITLE
No redirects happening

### ISSUE THREAD

**Issue by VOOM108** [catalyst/moodle-tool_redirects#6]
I installed the plugin via zip-file on Moodle 3.9, and checked "redirect Admins". I entered: 

`/course/index.php?categoryid=120=>/local/dash/dashboard.php?id=2`

(the target being a Dash-Dashboard, the link is valid)

But: nothing happens...

We are on nginx, otherwise I would have simply edited the .htaccess.

**Comment by dmitriim** [comment]
Hi @VOOM108  
The first part of your rule should be a regex. Please read docs: Each line should be a redirect rule like [**php regex** of URL to redirect from]=>[URL to redirect to]. E.g. /my/=>/course/view.php?id=2

Please try something like following and let me know if that worked for you 

`#/course/index.php\?categoryid=120#=>/local/dash/dashboard.php?id=2`
